parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     rajesh_symfony22_sonata
    database_user:     mysql_u
    database_password: mysql_p

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            1d37bb9e5d610c63a0ca01bbc5cab72
